name: Update FOSSA Policy

on:
  push:
    branches:
      - main

jobs:
  update-fossa-policy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests

    - name: Determine changed policy files
      id: changed_files
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep 'policies/.*\.yml' || echo "")
        echo "CHANGED_POLICY_FILES=$CHANGED_FILES" >> $GITHUB_ENV

    - name: Run update_fossa_policy.py if there are changed policy files
      if: env.CHANGED_POLICY_FILES != ''
      env:
        FOSSA_ACCESS_TOKEN: ${{ secrets.FOSSA_ACCESS_TOKEN }}
        CHANGED_POLICY_FILES: ${{ env.CHANGED_POLICY_FILES }}
      run: |
        python update_fossa_policy.py
